# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d551db6cad29cd51b02b3021a442b093711f004c5392dbc9036f255487a6ac8939d068dd95da3f94324b3755c61cb5f82b81b5bee49b240aaae3f915d04c67ef

test:
  secret_key_base: ca14441f44d1ba8ee6b24ad34be2bbc44d1b0807cfc3d8f825d1460cda7471d5b75a0c7c9c621a565a853dd223edec7db7305a1b00e54b638e079b37df8e77f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
